### ISSUE TITLE
能否和mockjs搭配使用？

### ISSUE THREAD

**Issue by djkloop** [alovajs/mock#7]
### 问题是什么

能否和mockjs搭配使用？mockjs在造假数据上很方便。

### 环境

- 浏览器：edge chrome latest
- 系统信息：windows 10
- 其他版本信息

### 在线例子

否

### 其他

其他信息

**Comment by JOU-amjs** [comment]
sorry，迟到了。
可以的，你可以按以下方式来配合使用
```javascript
import { defineMock } from '@alova/mock';

export default defineMock({
  '/api1': Mock.mock({
    'id|1-10000': 100
  })
});
```

如果你不需要使用`@alova/mock`提供的特性，你也可以直接使用`mockjs`进行数据模拟。
